package com.taller.m01.service;

import com.taller.m01.exception.ApiException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
import java.nio.file.*;
import java.util.*;

@Service
/**
 * Stores client photographs outside public static resources.
 *
 * <p>Each upload is validated by declared MIME type and binary signature, saved with a UUID, and
 * resolved only from a normalized private directory. The caller registers rollback cleanup when a
 * transaction fails.</p>
 */
public class ClientePhotoStorage {
    private static final long MAX_BYTES = 15L * 1024 * 1024;
    private static final String INVALID_PHOTO_MESSAGE = "La fotografía debe ser JPEG, PNG o WebP y no puede superar los 15 MB.";
    private final Path storageDirectory;

    public ClientePhotoStorage(@Value("${app.client-photo.storage-directory:./uploads/clientes}") String configuredDirectory) {
        storageDirectory = Paths.get(configuredDirectory).toAbsolutePath().normalize();
    }

    /**
     * Validates an optional multipart image before any client record is persisted.
     *
     * @param fotografia absent for an optional photo, otherwise a non-empty JPEG, PNG or WebP file
     * @return content and safe extension inferred from matching MIME type and binary signature, or {@code null} when absent
     * @throws ApiException with 400 when an attached file is empty, oversized, false or has an unsupported MIME/signature
     */
    public FotografiaValidada validar(MultipartFile fotografia) {
        if (fotografia == null) return null;
        if (fotografia.isEmpty() || fotografia.getSize() > MAX_BYTES || !esMimePermitido(fotografia.getContentType())) throw fotoInvalida();
        try {
            byte[] content = fotografia.getBytes();
            TipoFotografia tipo = detectarTipo(content);
            if (tipo == null || !tipo.mediaType().equalsIgnoreCase(fotografia.getContentType())) throw fotoInvalida();
            return new FotografiaValidada(content, tipo.extension());
        } catch (ApiException ex) {
            throw ex;
        } catch (IOException ex) {
            throw fotoInvalida();
        }
    }

    /**
     * Writes previously validated bytes with a generated UUID; original names and client paths are ignored.
     *
     * @param fotografia validated content and trusted extension
     * @return private file reference persisted in MySQL, never an absolute path
     * @throws ApiException with 500 when private storage cannot be written
     */
    public String guardar(FotografiaValidada fotografia) {
        if (fotografia == null) return null;
        try {
            Files.createDirectories(storageDirectory);
            String reference = UUID.randomUUID() + fotografia.extension();
            Path target = storageDirectory.resolve(reference).normalize();
            if (!target.startsWith(storageDirectory)) throw new ApiException(HttpStatus.BAD_REQUEST, "FOTOGRAFIA_INVALIDA", "La referencia de fotografía es inválida.");
            Files.write(target, fotografia.contenido(), StandardOpenOption.CREATE_NEW);
            return reference;
        } catch (ApiException ex) {
            throw ex;
        } catch (IOException ex) {
            throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR, "FOTOGRAFIA_ALMACENAMIENTO", "No fue posible almacenar la fotografía.");
        }
    }

    /**
     * Resolves a private, UUID-shaped photo reference without exposing a storage directory.
     *
     * @param referencia stored safe reference
     * @return readable resource and inferred response MIME type
     * @throws ApiException with 404 for absent, malformed or unreadable files
     */
    public FotoLeida leer(String referencia) {
        if (referencia == null || !referencia.matches("[0-9a-f-]{36}\\.(jpg|png|webp)")) throw noEncontrada();
        try {
            Path target = storageDirectory.resolve(referencia).normalize();
            if (!target.startsWith(storageDirectory) || !Files.isRegularFile(target)) throw noEncontrada();
            Resource resource = new UrlResource(target.toUri());
            if (!resource.isReadable()) throw noEncontrada();
            return new FotoLeida(resource, tipoPorReferencia(referencia).mediaType());
        } catch (IOException ex) {
            throw noEncontrada();
        }
    }

    /**
     * Deletes a transaction-orphaned private file only when its reference matches the UUID policy.
     *
     * @param referencia safe reference generated by this service
     */
    public void eliminarSiExiste(String referencia) {
        if (referencia == null || !referencia.matches("[0-9a-f-]{36}\\.(jpg|png|webp)")) return;
        try {
            Path target = storageDirectory.resolve(referencia).normalize();
            if (target.startsWith(storageDirectory)) Files.deleteIfExists(target);
        } catch (IOException ignored) { }
    }

    public record FotografiaValidada(byte[] contenido, String extension) { }
    public record FotoLeida(Resource resource, String mediaType) { }
    /** Builds the safe absence response for a non-public photo reference. */
    private ApiException noEncontrada() { return new ApiException(HttpStatus.NOT_FOUND, "FOTOGRAFIA_NO_ENCONTRADA", "La fotografía solicitada no existe."); }
    /** Builds the shared safe response for unsupported or untrusted image data. */
    private ApiException fotoInvalida() { return new ApiException(HttpStatus.BAD_REQUEST, "FOTOGRAFIA_INVALIDA", INVALID_PHOTO_MESSAGE); }
    /** Allows only the three image MIME values supported by this use case. */
    private boolean esMimePermitido(String mimeType) { return mimeType != null && (mimeType.equalsIgnoreCase("image/jpeg") || mimeType.equalsIgnoreCase("image/png") || mimeType.equalsIgnoreCase("image/webp")); }
    /** Infers the response MIME type from an already validated private extension. */
    private TipoFotografia tipoPorReferencia(String reference) { return reference.endsWith(".jpg") ? TipoFotografia.JPEG : reference.endsWith(".png") ? TipoFotografia.PNG : TipoFotografia.WEBP; }
    /** Detects a permitted image by magic bytes rather than its filename. */
    private TipoFotografia detectarTipo(byte[] content) {
        if (content.length >= 3 && (content[0] & 0xFF) == 0xFF && (content[1] & 0xFF) == 0xD8 && (content[2] & 0xFF) == 0xFF) return TipoFotografia.JPEG;
        if (content.length >= 8 && (content[0] & 0xFF) == 0x89 && content[1] == 0x50 && content[2] == 0x4E && content[3] == 0x47 && content[4] == 0x0D && content[5] == 0x0A && content[6] == 0x1A && content[7] == 0x0A) return TipoFotografia.PNG;
        if (content.length >= 12 && content[0] == 'R' && content[1] == 'I' && content[2] == 'F' && content[3] == 'F' && content[8] == 'W' && content[9] == 'E' && content[10] == 'B' && content[11] == 'P') return TipoFotografia.WEBP;
        return null;
    }
    private enum TipoFotografia {
        JPEG(".jpg", "image/jpeg"), PNG(".png", "image/png"), WEBP(".webp", "image/webp");
        private final String extension; private final String mediaType;
        TipoFotografia(String extension, String mediaType) { this.extension = extension; this.mediaType = mediaType; }
        String extension() { return extension; } String mediaType() { return mediaType; }
    }
}
