<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ChevronLeft, ChevronRight, ShieldCheck } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import UiAlert from '../components/UiAlert.vue'
import { api, apiError } from '../api/client'
const events=ref([]),meta=reactive({page:0,size:20,totalElements:0,totalPages:0}),error=ref(''),loading=ref(false)
async function load(page=meta.page){loading.value=true;try{const{data}=await api.get('/audit',{params:{page,size:meta.size}});events.value=data.content;Object.assign(meta,data)}catch(e){error.value=apiError(e)}finally{loading.value=false}}
onMounted(()=>load(0))
</script>
<template><AppShell title="Auditoría de seguridad" subtitle="Eventos seguros sin contraseñas, hashes, códigos ni tokens"><UiAlert :message="error"/><section class="card mt-4 overflow-hidden"><div v-if="loading" class="p-10 text-center text-slate-500">Cargando eventos…</div><div v-else-if="!events.length" class="p-12 text-center"><ShieldCheck class="mx-auto text-slate-300" :size="34"/><p class="mt-3 font-bold">Aún no hay eventos</p></div><div v-else class="overflow-x-auto"><table class="w-full min-w-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Fecha</th><th class="px-5 py-4">Acción</th><th class="px-5 py-4">Responsable</th><th class="px-5 py-4">Afectado</th><th class="px-5 py-4">IP</th><th class="px-5 py-4">Detalle seguro</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="event in events" :key="event.id"><td class="whitespace-nowrap px-5 py-4 text-slate-500">{{new Date(event.createdAt).toLocaleString()}}</td><td class="px-5 py-4"><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-800">{{event.action}}</span></td><td class="px-5 py-4">{{event.actor}}</td><td class="px-5 py-4">{{event.target||'—'}}</td><td class="px-5 py-4 font-mono text-xs text-slate-500">{{event.ipAddress||'—'}}</td><td class="px-5 py-4 text-slate-600">{{event.details}}</td></tr></tbody></table></div><div class="flex items-center justify-between border-t border-slate-100 px-5 py-4"><span class="text-sm text-slate-500">{{meta.totalElements}} eventos</span><div class="flex items-center gap-2"><button class="btn-ghost p-2" :disabled="meta.page===0" @click="load(meta.page-1)"><ChevronLeft :size="18"/></button><span class="text-sm font-bold">{{meta.page+1}} / {{Math.max(1,meta.totalPages)}}</span><button class="btn-ghost p-2" :disabled="meta.page+1>=meta.totalPages" @click="load(meta.page+1)"><ChevronRight :size="18"/></button></div></div></section></AppShell></template>
