<script setup>
import { ref } from 'vue'
import { Camera, CarFront, Eraser, Save, ShieldCheck, UserRoundPlus } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import ConfirmationModal from '../components/ConfirmationModal.vue'
import { useClienteFacade } from '../facades/clienteFacade'

const clienteFacade = useClienteFacade()
const confirmarLimpieza = ref(false)
const seleccionarFoto = (event) => clienteFacade.seleccionarFotografia(event.target.files?.[0])
const solicitarLimpieza = () => { if (clienteFacade.tieneCambios) confirmarLimpieza.value = true; else clienteFacade.cancelarCaptura() }
const confirmar = () => { confirmarLimpieza.value = false; clienteFacade.cancelarCaptura() }
</script>

<template>
  <AppShell title="Registro de clientes" subtitle="Alta segura de clientes para el taller">
    <div class="mx-auto max-w-6xl">
      <section class="control-hero overflow-hidden rounded-3xl p-6 text-white sm:p-8"><div class="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-amber-200">Recepción · Expediente inicial</p><h2 class="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Registra a quien confía su vehículo contigo.</h2><p class="mt-3 max-w-3xl text-sm leading-6 text-slate-200">La información se valida antes de guardarse. Correo, teléfono y nombre con fecha de nacimiento evitan expedientes duplicados.</p></div><div class="flex items-center gap-3 rounded-2xl border border-white/15 bg-white/10 p-4 text-sm text-cyan-100"><ShieldCheck :size="25"/><span>Acceso controlado por permiso</span></div></div></section>

      <form class="mt-6" novalidate @submit.prevent="clienteFacade.registrarCliente">
        <div class="grid gap-6 xl:grid-cols-[1fr_310px]">
          <div class="space-y-6">
            <section class="card p-6 sm:p-8"><div class="flex items-start gap-3 border-b border-slate-100 pb-5"><div class="rounded-xl bg-cyan-50 p-2.5 text-cyan-700"><UserRoundPlus :size="21"/></div><div><h3 class="font-black text-slate-950">Datos personales</h3><p class="mt-1 text-sm text-slate-500">Los campos con <span class="font-bold text-rose-600">*</span> son obligatorios.</p></div></div>
              <div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Nombre completo <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.nombreCompleto" class="field" :class="{'field-invalid': clienteFacade.errors.nombreCompleto}" autocomplete="name" placeholder="María López Hernández"/><p v-if="clienteFacade.errors.nombreCompleto" class="field-error">{{ clienteFacade.errors.nombreCompleto }}</p></label><label><span class="label">Fecha de nacimiento <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.fechaNacimiento" class="field" :class="{'field-invalid': clienteFacade.errors.fechaNacimiento}" :max="clienteFacade.today" type="date"/><p v-if="clienteFacade.errors.fechaNacimiento" class="field-error">{{ clienteFacade.errors.fechaNacimiento }}</p></label><div><span class="label">Edad calculada</span><div class="flex h-12 items-center rounded-xl border border-slate-200 bg-slate-50 px-4"><span class="font-black text-slate-900">{{ clienteFacade.edad === null ? '—' : `${clienteFacade.edad} años` }}</span><span class="ml-auto text-xs text-slate-500">No editable</span></div></div><label class="sm:col-span-2"><span class="label">Contacto alternativo</span><input v-model="clienteFacade.form.contactoAlternativo" class="field" :class="{'field-invalid': clienteFacade.errors.contactoAlternativo}" placeholder="Nombre de contacto opcional"/><p v-if="clienteFacade.errors.contactoAlternativo" class="field-error">{{ clienteFacade.errors.contactoAlternativo }}</p></label></div>
            </section>

            <section class="card p-6 sm:p-8"><div class="flex items-start gap-3 border-b border-slate-100 pb-5"><div class="rounded-xl bg-amber-50 p-2.5 text-amber-700"><CarFront :size="21"/></div><div><h3 class="font-black text-slate-950">Contacto</h3><p class="mt-1 text-sm text-slate-500">El correo y teléfono personales identifican de forma única al cliente.</p></div></div>
              <div class="mt-6 grid gap-5 sm:grid-cols-2"><label><span class="label">Teléfono personal <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.telefonoPersonal" class="field" :class="{'field-invalid': clienteFacade.errors.telefonoPersonal}" autocomplete="tel" inputmode="tel" placeholder="555 123 4567"/><p v-if="clienteFacade.errors.telefonoPersonal" class="field-error">{{ clienteFacade.errors.telefonoPersonal }}</p></label><label><span class="label">Teléfono de trabajo</span><input v-model="clienteFacade.form.telefonoTrabajo" class="field" :class="{'field-invalid': clienteFacade.errors.telefonoTrabajo}" inputmode="tel" placeholder="Opcional"/><p v-if="clienteFacade.errors.telefonoTrabajo" class="field-error">{{ clienteFacade.errors.telefonoTrabajo }}</p></label><label><span class="label">Correo electrónico personal <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.emailPersonal" class="field" :class="{'field-invalid': clienteFacade.errors.emailPersonal}" autocomplete="email" type="email" placeholder="cliente@correo.com"/><p v-if="clienteFacade.errors.emailPersonal" class="field-error">{{ clienteFacade.errors.emailPersonal }}</p></label><label><span class="label">Correo electrónico de trabajo</span><input v-model="clienteFacade.form.emailTrabajo" class="field" :class="{'field-invalid': clienteFacade.errors.emailTrabajo}" type="email" placeholder="Opcional"/><p v-if="clienteFacade.errors.emailTrabajo" class="field-error">{{ clienteFacade.errors.emailTrabajo }}</p></label></div>
            </section>

            <section class="card p-6 sm:p-8"><div class="flex items-start gap-3 border-b border-slate-100 pb-5"><div class="rounded-xl bg-slate-100 p-2.5 text-slate-700"><CarFront :size="21"/></div><div><h3 class="font-black text-slate-950">Dirección</h3><p class="mt-1 text-sm text-slate-500">Información necesaria para el expediente del cliente.</p></div></div>
              <div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Calle y número <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.direccion.calleNumero" class="field" :class="{'field-invalid': clienteFacade.errors.calleNumero}" autocomplete="street-address" placeholder="Avenida del Motor 123"/><p v-if="clienteFacade.errors.calleNumero" class="field-error">{{ clienteFacade.errors.calleNumero }}</p></label><label><span class="label">Colonia <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.direccion.colonia" class="field" :class="{'field-invalid': clienteFacade.errors.colonia}" placeholder="Centro"/><p v-if="clienteFacade.errors.colonia" class="field-error">{{ clienteFacade.errors.colonia }}</p></label><label><span class="label">Código postal <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.direccion.codigoPostal" class="field" :class="{'field-invalid': clienteFacade.errors.codigoPostal}" autocomplete="postal-code" inputmode="numeric" maxlength="5" placeholder="64000"/><p v-if="clienteFacade.errors.codigoPostal" class="field-error">{{ clienteFacade.errors.codigoPostal }}</p></label><label><span class="label">Municipio <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.direccion.municipio" class="field" :class="{'field-invalid': clienteFacade.errors.municipio}" placeholder="Monterrey"/><p v-if="clienteFacade.errors.municipio" class="field-error">{{ clienteFacade.errors.municipio }}</p></label><label><span class="label">Estado <span class="text-rose-600">*</span></span><input v-model="clienteFacade.form.direccion.estado" class="field" :class="{'field-invalid': clienteFacade.errors.estado}" placeholder="Nuevo León"/><p v-if="clienteFacade.errors.estado" class="field-error">{{ clienteFacade.errors.estado }}</p></label></div>
            </section>
          </div>

          <aside class="space-y-6 xl:sticky xl:top-28 xl:self-start"><section class="card p-6"><div class="flex items-center gap-3"><div class="rounded-xl bg-cyan-50 p-2.5 text-cyan-700"><Camera :size="20"/></div><div><h3 class="font-black text-slate-950">Fotografía</h3><p class="text-xs text-slate-500">Opcional · JPEG, PNG o WebP · Máx. 5 MB</p></div></div><label class="mt-5 flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-cyan-200 bg-cyan-50/40 p-5 text-center transition hover:border-cyan-400 hover:bg-cyan-50"><img v-if="clienteFacade.vistaPrevia" :src="clienteFacade.vistaPrevia" alt="Vista previa de la fotografía seleccionada" class="mb-3 h-38 w-38 rounded-2xl object-cover shadow-md"/><Camera v-else :size="33" class="mb-3 text-cyan-700"/><span class="text-sm font-bold text-slate-800">{{ clienteFacade.fotografia ? 'Cambiar fotografía' : 'Seleccionar fotografía' }}</span><span class="mt-1 text-xs text-slate-500">No se usa el nombre original del archivo.</span><input class="sr-only" accept="image/jpeg,image/png,image/webp" type="file" @change="seleccionarFoto"/></label><p v-if="clienteFacade.errors.fotografia" class="field-error">{{ clienteFacade.errors.fotografia }}</p></section><section class="card p-5"><h3 class="font-black text-slate-950">Antes de guardar</h3><ul class="mt-3 space-y-2 text-sm leading-5 text-slate-600"><li class="flex gap-2"><ShieldCheck :size="17" class="mt-0.5 shrink-0 text-emerald-600"/>Se validarán duplicados por correo, teléfono y fecha de nacimiento.</li><li class="flex gap-2"><ShieldCheck :size="17" class="mt-0.5 shrink-0 text-emerald-600"/>Los datos se guardan en una transacción.</li></ul></section></aside>
        </div>
        <div class="card mt-6 flex flex-col-reverse gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm text-slate-500">La edad se calcula con la fecha de nacimiento y no se almacena como dato editable.</p><div class="flex flex-col-reverse gap-3 sm:flex-row"><button type="button" class="btn-ghost" :disabled="clienteFacade.isSubmitting" @click="solicitarLimpieza"><Eraser :size="17"/>Limpiar</button><button type="submit" class="btn-primary bg-cyan-700 hover:bg-cyan-600" :disabled="clienteFacade.isSubmitting"><Save :size="17"/>{{ clienteFacade.isSubmitting ? 'Registrando cliente…' : 'Guardar cliente' }}</button></div></div>
      </form>
    </div>
    <ConfirmationModal v-if="confirmarLimpieza" title="¿Deseas limpiar el formulario?" message="Los datos capturados se perderán." confirm-label="Sí, limpiar" @cancel="confirmarLimpieza = false" @confirm="confirmar"/>
  </AppShell>
</template>
