<script setup>
import { onMounted, ref } from 'vue'
import { Save, X } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import UiAlert from '../components/UiAlert.vue'
import { api, apiError } from '../api/client'
const roles=ref([]),permissions=ref([]),loading=ref(false),error=ref(''),success=ref(''),selected=ref(null),checked=ref([]),saving=ref(false)
async function load(){loading.value=true;try{const [r,p]=await Promise.all([api.get('/roles'),api.get('/permissions')]);roles.value=r.data;permissions.value=p.data}catch(e){error.value=apiError(e)}finally{loading.value=false}}
function open(role){selected.value=role;checked.value=role.permissions.map(p=>p.id);error.value=''}
async function save(){saving.value=true;try{const {data}=await api.put(`/roles/${selected.value.id}/permissions`,{permissionIds:checked.value});roles.value=roles.value.map(r=>r.id===data.id?data:r);selected.value=data;success.value='Permisos actualizados.'}catch(e){error.value=apiError(e)}finally{saving.value=false}}
onMounted(load)
</script>
<template><AppShell title="Roles y permisos" subtitle="Matriz de autorización validada por el backend"><UiAlert type="success" :message="success"/><UiAlert class="mb-4" :message="error"/><div v-if="loading" class="card p-10 text-center text-slate-500">Cargando matriz…</div><section v-else class="grid gap-5 xl:grid-cols-2"><article v-for="role in roles" :key="role.id" class="card p-6"><div class="flex items-start justify-between gap-4"><div><span class="text-xs font-black tracking-wider text-amber-600">{{role.code}}</span><h2 class="mt-1 text-xl font-black">{{role.name}}</h2><p class="mt-2 text-sm text-slate-500">{{role.description}}</p></div><button v-if="role.code!=='SUPERADMIN'" class="btn-ghost" @click="open(role)">Configurar</button></div><div class="mt-5 flex flex-wrap gap-2"><span v-for="permission in role.permissions" :key="permission.id" class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{{permission.name}}</span></div></article></section><div v-if="selected" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form class="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl" @submit.prevent="save"><div class="flex justify-between"><div><h2 class="text-xl font-black">Permisos: {{selected.name}}</h2><p class="mt-1 text-sm text-slate-500">Los cambios quedan registrados en auditoría.</p></div><button class="p-2" type="button" @click="selected=null"><X/></button></div><div class="mt-5 grid gap-2 sm:grid-cols-2"><label v-for="permission in permissions" :key="permission.id" class="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><input v-model="checked" :value="permission.id" type="checkbox" class="mt-1 accent-amber-500"/><span><b class="block text-sm">{{permission.name}}</b><span class="text-xs text-slate-500">{{permission.description}}</span></span></label></div><div class="mt-6 flex justify-end gap-3"><button class="btn-ghost" type="button" @click="selected=null">Cancelar</button><button class="btn-primary" :disabled="saving"><Save :size="17"/>{{saving?'Guardando…':'Guardar permisos'}}</button></div></form></div></AppShell></template>
