<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Plus, Search, Pencil, LockKeyhole, UserCheck, ChevronLeft, ChevronRight, X } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import UiAlert from '../components/UiAlert.vue'
import { api, apiError } from '../api/client'

const users=ref([]), roles=ref([]), meta=reactive({page:0,size:10,totalPages:0,totalElements:0}), filters=reactive({query:'',role:'',status:''}), loading=ref(false), error=ref(''), success=ref(''), modal=ref(false), editing=ref(null), saving=ref(false)
const form=reactive({fullName:'',email:'',phone:'',temporaryPassword:'',confirmation:'',roleCode:'',status:'ACTIVE'})
const passwordOk=computed(()=>form.temporaryPassword.length>=8&&/[A-Z]/.test(form.temporaryPassword)&&/[a-z]/.test(form.temporaryPassword)&&/\d/.test(form.temporaryPassword)&&/[^A-Za-z0-9]/.test(form.temporaryPassword)&&form.temporaryPassword===form.confirmation)
function resetForm(){Object.assign(form,{fullName:'',email:'',phone:'',temporaryPassword:'',confirmation:'',roleCode:roles.value.find(r=>r.code!=='SUPERADMIN')?.code||'',status:'ACTIVE'})}
async function load(page=meta.page){loading.value=true;error.value='';try{const {data}=await api.get('/users',{params:{...filters,status:filters.status||undefined,page,size:meta.size}});users.value=data.content;Object.assign(meta,data)}catch(e){error.value=apiError(e)}finally{loading.value=false}}
async function loadRoles(){try{const {data}=await api.get('/roles');roles.value=data}catch(e){error.value=apiError(e)}}
function openCreate(){editing.value=null;resetForm();modal.value=true;success.value=''}
function openEdit(user){editing.value=user;Object.assign(form,{fullName:user.fullName,email:user.email,phone:user.phone||'',temporaryPassword:'',confirmation:'',roleCode:user.primaryRole,status:user.status});modal.value=true;success.value=''}
async function save(){error.value=''; if(!form.fullName||!form.email||!form.roleCode){error.value='Complete los campos obligatorios.';return} if(!editing.value&&!passwordOk.value){error.value='La contraseña temporal debe cumplir la política y coincidir.';return}saving.value=true;try{if(editing.value){await api.put(`/users/${editing.value.id}`,{fullName:form.fullName,email:form.email,phone:form.phone||null});if(form.roleCode!==editing.value.primaryRole)await api.patch(`/users/${editing.value.id}/role`,{roleCode:form.roleCode});success.value='Usuario actualizado correctamente.'}else{await api.post('/users',{...form,phone:form.phone||null});success.value='Usuario creado. Deberá cambiar su contraseña temporal.'}modal.value=false;await load()}catch(e){error.value=apiError(e)}finally{saving.value=false}}
async function setStatus(user){const next=user.status==='ACTIVE'?'INACTIVE':'ACTIVE';if(!confirm(`${next==='ACTIVE'?'Activar':'Desactivar'} a ${user.fullName}?`))return;try{await api.patch(`/users/${user.id}/status`,{status:next});success.value='Estado actualizado.';await load()}catch(e){error.value=apiError(e)}}
async function unlock(user){if(!confirm(`¿Desbloquear la cuenta de ${user.fullName}?`))return;try{await api.post(`/users/${user.id}/unlock`);success.value='Cuenta desbloqueada.';await load()}catch(e){error.value=apiError(e)}}
function statusClass(status){return `status-${status.toLowerCase()}`}
let timer;watch(()=>[filters.query,filters.role,filters.status],()=>{clearTimeout(timer);timer=setTimeout(()=>load(0),300)})
onMounted(async()=>{await loadRoles();await load(0)})
</script>
<template><AppShell title="Administración de usuarios" subtitle="Cuentas, estados, roles y contraseñas temporales"><UiAlert type="success" :message="success"/><UiAlert class="mb-4" :message="error"/><section class="card mt-4 p-4"><div class="flex flex-col gap-3 xl:flex-row xl:items-center"><div class="relative flex-1"><Search class="absolute left-3 top-3 text-slate-400" :size="19"/><input v-model.trim="filters.query" class="field pl-10" placeholder="Buscar por nombre o correo"/></div><select v-model="filters.role" class="field xl:w-52"><option value="">Todos los roles</option><option v-for="role in roles" :key="role.code" :value="role.code">{{role.name}}</option></select><select v-model="filters.status" class="field xl:w-44"><option value="">Todos los estados</option><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option><option value="BLOCKED">Bloqueado</option></select><button class="btn-primary" @click="openCreate"><Plus :size="18"/>Registrar usuario</button></div></section>
  <section class="card mt-5 overflow-hidden"><div v-if="loading" class="p-12 text-center text-slate-500">Cargando usuarios…</div><div v-else-if="!users.length" class="p-12 text-center"><p class="font-bold">No hay resultados</p><p class="mt-1 text-sm text-slate-500">Ajusta los filtros o registra la primera cuenta.</p></div><div v-else class="overflow-x-auto"><table class="w-full min-w-210 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Usuario</th><th class="px-5 py-4">Rol</th><th class="px-5 py-4">Estado</th><th class="px-5 py-4">Último acceso</th><th class="px-5 py-4 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="user in users" :key="user.id"><td class="px-5 py-4"><p class="font-bold text-slate-900">{{user.fullName}}</p><p class="text-slate-500">{{user.email}}</p></td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{{user.primaryRole}}</span></td><td class="px-5 py-4"><span :class="statusClass(user.status)" class="rounded-full px-2.5 py-1 text-xs font-bold">{{user.status==='ACTIVE'?'Activo':user.status==='INACTIVE'?'Inactivo':'Bloqueado'}}</span></td><td class="px-5 py-4 text-slate-500">{{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():'Sin acceso'}}</td><td class="px-5 py-4"><div v-if="!user.initialAdmin && !user.roles.includes('SUPERADMIN')" class="flex justify-end gap-2"><button class="btn-ghost p-2" title="Editar" @click="openEdit(user)"><Pencil :size="17"/></button><button v-if="user.status==='BLOCKED'" class="btn-ghost p-2" title="Desbloquear" @click="unlock(user)"><LockKeyhole :size="17"/></button><button v-else class="btn-ghost p-2" :title="user.status==='ACTIVE'?'Desactivar':'Activar'" @click="setStatus(user)"><UserCheck :size="17"/></button></div><span v-else class="text-xs text-slate-400">Protegido</span></td></tr></tbody></table></div><div class="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-sm"><span class="text-slate-500">{{meta.totalElements}} registros</span><div class="flex gap-2"><button class="btn-ghost p-2" :disabled="meta.page===0" @click="load(meta.page-1)"><ChevronLeft :size="18"/></button><span class="px-2 py-2 font-bold">{{meta.page+1}} / {{Math.max(meta.totalPages,1)}}</span><button class="btn-ghost p-2" :disabled="meta.page+1>=meta.totalPages" @click="load(meta.page+1)"><ChevronRight :size="18"/></button></div></div></section>
  <div v-if="modal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form class="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" @submit.prevent="save"><div class="flex items-start justify-between"><div><h2 class="text-xl font-black">{{editing?'Editar usuario':'Registrar usuario'}}</h2><p class="mt-1 text-sm text-slate-500">{{editing?'Actualiza los datos y rol de la cuenta.':'La persona deberá cambiar la contraseña temporal al entrar.'}}</p></div><button class="rounded-lg p-2 hover:bg-slate-100" type="button" @click="modal=false"><X/></button></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Nombre completo *</span><input v-model.trim="form.fullName" class="field"/></label><label><span class="label">Correo *</span><input v-model.trim="form.email" class="field" type="email"/></label><label><span class="label">Teléfono</span><input v-model.trim="form.phone" class="field" placeholder="555 123 4567"/></label><template v-if="!editing"><label><span class="label">Contraseña temporal *</span><input v-model="form.temporaryPassword" class="field" type="password"/></label><label><span class="label">Confirmar contraseña *</span><input v-model="form.confirmation" class="field" type="password"/></label></template><label><span class="label">Rol *</span><select v-model="form.roleCode" class="field"><option v-for="role in roles.filter(r=>r.code!=='SUPERADMIN')" :key="role.code" :value="role.code">{{role.name}}</option></select></label><label v-if="!editing"><span class="label">Estado</span><select v-model="form.status" class="field"><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></label></div><p v-if="!editing" class="mt-3 text-xs text-slate-500">Contraseña: 8+ caracteres, mayúscula, minúscula, número y símbolo.</p><UiAlert class="mt-4" :message="error"/><div class="mt-6 flex justify-end gap-3"><button class="btn-ghost" type="button" @click="modal=false">Cancelar</button><button class="btn-primary" :disabled="saving">{{saving?'Guardando…':'Guardar usuario'}}</button></div></form></div>
</AppShell></template>
